20 july 2024; add svr script and functions; fig improvements; makefile improvements

diff --git a/draft/Makefile b/draft/Makefile
--- a/draft/Makefile
+++ b/draft/Makefile
@@ -1,24 +1,43 @@
 # Makefile config
 SHELL = /bin/bash -o pipefail
+WORKDIR = $(shell pwd)
+MAINDIR = $(shell dirname $(WORKDIR))
+ASSETSDIR = $(WORKDIR)/assets
+UNAMES := $(shell uname -s)
 DATE = $(shell date +"%d-%m-%Y")
 DATELONG = $(shell date +"%d-%B-%Y")
 # Logging
-LOGFILE := assets/log/log-$(shell date +"%d-%m-%Y")
+LOGDIR = $(ASSETSDIR)/log
+LOGFILE := $(LOGDIR)/log-$(shell date +"%d-%m-%Y")
 LOG := 2>&1 | tee -a $(LOGFILE)
 # Manuscript
 MS = madnn
-# Notes and manuscript draft
-BIB = assets/bib/main.bib
-CSL = assets/bib/agu.csl
-AGUMETA = assets/pandoc/agu.yaml
-AGUTEMPLATE = assets/tex/template-agu.latex
-EIMETA = assets/pandoc/eisvogel.yaml
-EITEMPLATE = assets/tex/template-eisvogel.latex
-# Make clean
-DATAPURGE = assets/log assets/pandoc/benchmark-comps.md assets/pandoc/benchmark-times.md eisvogel-draft-madnn.pdf
-DATACLEAN = 
+# Figures
+FIGDIRMAIN = $(MAINDIR)/figs
+FIGDIRDRAFT = $(ASSETSDIR)/figs
+# Data
+DATADIR = $(ASSETSDIR)/data
+# Tex
+TEXDIR = $(ASSETSDIR)/tex
+AGUTEMPLATE = $(TEXDIR)/template-agu.latex
+EITEMPLATE = $(TEXDIR)/template-eisvogel.latex
+# Bib
+BIBDIR = $(ASSETSDIR)/bib
+BIB = $(BIBDIR)/main.bib
+CSL = $(BIBDIR)/agu.csl
+# Pandoc
+PANDIR = $(ASSETSDIR)/pandoc
+AGUMETA = $(PANDIR)/agu.yaml
+EIMETA = $(PANDIR)/eisvogel.yaml
+# Purging and cleaning
+DATAPURGE = \
+	$(LOGDIR) \
+	$(PANDIR)/benchmark-comps.md \
+	$(PANDIR)/benchmark-times.md \
+	eisvogel-draft-madnn.pdf
+DATACLEAN = $(DATADIR)
 FIGSPURGE =
-FIGSCLEAN = assets/figs
+FIGSCLEAN = $(FIGDIRDRAFT)
 
 agu: $(LOGFILE) $(AGUMETA) $(AGUTEMPLATE) $(MS).md
 	@pandoc $(MS).md \
@@ -52,14 +71,34 @@ eisvogel: $(LOGFILE) $(EIMETA) $(EITEMPLATE) $(MS).md
 		$(LOG)
 	@echo "=============================================" $(LOG)
 
-copy_figs: $(LOGFILE)
-	@echo "Copying figs ..." $(LOG)
-	@cp -r ../figs assets/
-	@echo "=============================================" $(LOG)
+copy_assets: $(LOGFILE) copy_data copy_figs
+
+copy_figs: $(LOGFILE) $(MS).md
+	@echo "Copying figs:" $(LOG)
+	@mkdir -p $(FIGDIRDRAFT)
+	@if [ ! -f "$(MS).md" ]; then \
+		echo "Error: The markdown file $(MS).md does not exist ..." $(LOG); \
+		exit 1; \
+	fi
+	@for pngfile in $$(grep -o -E '\([^\)]+\.png\)' $(MS).md | tr -d '()'); do \
+		basename=$$(basename $$pngfile); \
+		fullpath=$$(find $(FIGDIRMAIN) -type f -name $$basename); \
+		if [ -z "$$fullpath" ]; then \
+			echo "Warning: $$basename not found in $(FIGDIRMAIN)" $(LOG); \
+		else \
+			cp "$$fullpath" "$(FIGDIRDRAFT)/$$basename"; \
+			echo "	$$basename" $(LOG); \
+		fi \
+	done
+
+copy_data: $(LOGFILE)
+	@echo "Copying data ..." $(LOG)
+	@cp -r $(MAINDIR)/assets/data $(ASSETSDIR)
+	@(cd $(shell dirname $(WORKDIR)) && $(MAKE) write_tables)
 
 $(LOGFILE):
 	@if [ ! -e "$(LOGFILE)" ]; then \
-		mkdir -p assets/log; \
+		mkdir -p $(LOGDIR); \
 		touch $(LOGFILE); \
 	fi
 
@@ -70,4 +109,4 @@ clean: purge
 	@rm -rf $(DATACLEAN) $(FIGSCLEAN)
 	@rm -f *.{html,acr,alg,gz,glg,gls,ilg,nls,acn,glo,ist,lof,lot,nlo,aux,dvi,log,bbl,blg,brf,fls,toc,thm,out,fdb_latexmk,tex,pdf}
 
-.PHONY: eisvogel agu all purge clean
+.PHONY: create_conda_env find_conda_env copy_assets eisvogel agu all purge clean
